### ISSUE TITLE
Add answers to the quiz questions

### ISSUE THREAD

**Issue by MelkorNemesis** [enricopolanski/functional-programming#10]
Can you add answers to the quiz questions that pop up throughout the file?

For instance, I'm at this section "Order-derivable Semigroups" where there's this quiz question: `Quiz. Why is it so important that number is a total order?`. As a reader I do have some answer to that question, but I don't know if that answer is correct and have no way to validate it.

**Comment by enricopolanski** [comment]
Hi, this is a very nice suggestion.

How about we have a discussion about all the quizzes on the fp-ts channel or here in the comments and you may open a PR adding the Quiz answers?

**Comment by MelkorNemesis** [comment]
Sounds good to me. I'll do my best to get some extra time to do it.
