### ISSUE TITLE
Wrong example?

### ISSUE THREAD

**Issue by QimatLuo** [enricopolanski/functional-programming#26]
https://github.com/enricopolanski/functional-programming/blob/8cc74912f21607c779ec405ca32b2b2048b55d1c/README.md?plain=1#L2905

Should be `const idB = (n: number): number => n `?

**Comment by enricopolanski** [comment]
That is correct, would you like to open a pull request and fix this?

**Comment by QimatLuo** [comment]
https://github.com/enricopolanski/functional-programming/pull/32
