### ISSUE TITLE
Add instructions to run the examples

### ISSUE THREAD

**Issue by nicoabie** [enricopolanski/functional-programming#4]

**Comment by enricopolanski** [comment]
Hi @nicoabie, why do you feel there should be instructions to run the examples?

It is up to the user to run those in the environment they prefer or export the functions to run them in other code.

**Comment by nicoabie** [comment]
Hi @enricopolanski yes, given the fact that there is a package.json that list the dependencies and a tsconfig the project is runnable but there are no instructions.
Maybe adding to the scripts section to simply do npm run sampleN

**Comment by enricopolanski** [comment]
I see your point, would you like to submit a PR?
