### ISSUE TITLE
Suggestion: Would it be possible for to make a youtube presentation of this repo?

### ISSUE THREAD

**Issue by hansschenker** [enricopolanski/functional-programming#51]
Suggestion: Would it be possible for to make a youtube presentation of this repo? Thank's for publishing!

**Comment by enricopolanski** [comment]
@hansschenker @gcanti uses those slides as a reference for his courses and workshops.

The workshops take about 2 working days to go through the repo and they contain obviously more content, QAs, etc.

I don't think it is somewhat realistic to put all the necessary work to go through it for a number of views that would never compensate the amount of work.

**Comment by hansschenker** [comment]
Hi Enrico,

thank's for the message!
Anyway a good repo and thank you for publishing!

Have a nice day!
Gian
calling from Switzerland
