### ISSUE TITLE
Rewrite using Effect-ts

### ISSUE THREAD

**Issue by adrian-gierakowski** [enricopolanski/functional-programming#54]
since fp-ts (v3) has been [merged into the Effect ecosystem](https://dev.to/effect-ts/a-bright-future-for-effect-455m) it would be great to have this course rewritten using [Effect](https://github.com/Effect-TS)

**Comment by enricopolanski** [comment]
I don't understand where is the "issue".

**Comment by adrian-gierakowski** [comment]
I guess I should have opened a discussion instead. All the best for you!
